version: '2'
run:
  timeout: 10m
  tests: true
linters:
  enable:
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - unused
  - goimports
  - gofmt
  settings:
    goimports:
      local-prefixes: github.com/duynhne/user-service
